name: OCI Deployment

on:
  #To trigger manually
  workflow_dispatch:
  push:
    branches: [oci]

env:
  ENVIRONMENT: oci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: oci
      - name: Setting up Java
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "oracle"
      - name: Building urlscreenshot
        working-directory: ./urlscreenshot
        run: mvn clean install -DskipTests
      - name: Login to OCIR
        uses: docker/login-action@v3
        with:
          registry: ocir.us-ashburn-1.oci.oraclecloud.com
          username: ${{ secrets.OCI_PROD_DOCKER_USER_NAME }}
          password: ${{ secrets.OCI_PROD_CLI_AUTH_TOKEN }}
      - name: Docker version
        id: dockerVersion
        run: |
          VERSION=$(date '+%Y%m%d%H%M%S')
          echo "Setting version to ${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
      - name: Pushing URL Screenshot Auxillary Docker Image to OCI
        working-directory: ./urlscreenshot
        run: |
          docker build -t aux-urlimage:${{ steps.dockerVersion.outputs.VERSION }} .
          docker tag aux-urlimage:${{ steps.dockerVersion.outputs.VERSION }} ocir.us-ashburn-1.oci.oraclecloud.com/idfmutpuhiky/aux-urlimage:${{ steps.dockerVersion.outputs.VERSION }}
          docker push ocir.us-ashburn-1.oci.oraclecloud.com/idfmutpuhiky/aux-urlimage:${{ steps.dockerVersion.outputs.VERSION }}
          docker tag aux-urlimage:${{ steps.dockerVersion.outputs.VERSION }} ocir.us-ashburn-1.oci.oraclecloud.com/idfmutpuhiky/aux-urlimage:latest
          docker push ocir.us-ashburn-1.oci.oraclecloud.com/idfmutpuhiky/aux-urlimage:latest
